name: Build and deploy Node.js app to Azure Web App - iamhunt

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}" >> $GITHUB_ENV
          echo "MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "HH_CLIENT_ID=${{ secrets.HH_CLIENT_ID }}" >> $GITHUB_ENV
          echo "HH_CLIENT_SECRET=${{ secrets.HH_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "LINKEDIN_CLIENT_ID=${{ secrets.LINKEDIN_CLIENT_ID }}" >> $GITHUB_ENV
          echo "LINKEDIN_CLIENT_SECRET=${{ secrets.LINKEDIN_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "JOOBLE_REST_API=${{ secrets.JOOBLE_REST_API }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "GEMINI_AI_API_KEY=${{ secrets.GEMINI_AI_API_KEY }}" >> $GITHUB_ENV
          echo "GOOGLE_MAIL_APP_EMAIL=${{ secrets.GOOGLE_MAIL_APP_EMAIL }}" >> $GITHUB_ENV
          echo "GOOGLE_MAIL_APP_PASSWORD=${{ secrets.GOOGLE_MAIL_APP_PASSWORD }}" >> $GITHUB_ENV
          echo "CLIENT_SIDE_URL=${{ secrets.CLIENT_SIDE_URL }}" >> $GITHUB_ENV
          echo "SERVER_SIDE_URL=${{ secrets.SERVER_SIDE_URL }}" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          auth-type: 'secret'
          client-secret: ${{ secrets.AZUREAPPSERVICE_PASSWORD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'iamhunt'
          slot-name: 'Production'

      - name: Configure startup command in Azure Web App
        run: |
          az webapp config set --name iamhunt --resource-group iamhunt --startup-file "npm run server"
        env:
          AZUREAPPSERVICE_CLIENTID: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          AZUREAPPSERVICE_TENANTID: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          AZUREAPPSERVICE_SUBSCRIPTIONID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          AZUREAPPSERVICE_PASSWORD: ${{ secrets.AZUREAPPSERVICE_PASSWORD }}

      - name: Debug environment variables
        run: |
          echo "PORT=$PORT"
          echo "MONGO_DB_URI=$MONGO_DB_URI"
          echo "MONGO_DATABASE=$MONGO_DATABASE"
          echo "JWT_SECRET_KEY=$JWT_SECRET_KEY"
          echo "AWS_SECRET_KEY=$AWS_SECRET_KEY"
          echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY"
          echo "AWS_BUCKET_NAME=$AWS_BUCKET_NAME"
          echo "AWS_REGION=$AWS_REGION"
          echo "HH_CLIENT_ID=$HH_CLIENT_ID"
          echo "HH_CLIENT_SECRET=$HH_CLIENT_SECRET"
          echo "LINKEDIN_CLIENT_ID=$LINKEDIN_CLIENT_ID"
          echo "LINKEDIN_CLIENT_SECRET=$LINKEDIN_CLIENT_SECRET"
          echo "JOOBLE_REST_API=$JOOBLE_REST_API"
          echo "OPENAI_API_KEY=$OPENAI_API_KEY"
          echo "GEMINI_AI_API_KEY=$GEMINI_AI_API_KEY"
          echo "GOOGLE_MAIL_APP_EMAIL=$GOOGLE_MAIL_APP_EMAIL"
          echo "GOOGLE_MAIL_APP_PASSWORD=$GOOGLE_MAIL_APP_PASSWORD"
          echo "CLIENT_SIDE_URL=$CLIENT_SIDE_URL"
          echo "SERVER_SIDE_URL=$SERVER_SIDE_URL"
